# fly.toml file generated for stripe-payments-backend on 2023-01-10T08:04:09Z

app = "stripe-payments-backend"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "artemkolodko/stripe-payments-backend"

[env]
  DB_NAME = "stripe_db"
  DB_USERNAME = "postgres"
  DB_PORT = "5433"
  CLIENT_URL = "https://stripefront.demos.country"
  RPC_URL = "https://api.s0.t.hmny.io"
  ONE_COUNTRY_CONTRACT_ADDRESS = "0x3cc3c5f98ac3ff544279919dfcebfb7afe03a2ca"
  VIDEO_REELS_CONTRACT_ADDRESS = "0x9c125e45d2d9e7152e7dabc4edd7e063bc27708a"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
